### ISSUE TITLE
Decode the $GPGGA to get height information

### ISSUE THREAD

**Issue by generationmake** [107-systems/107-Arduino-NMEA-Parser#15]
Could be useful for any flying object.

**Comment by aentinger** [comment]
Hi @generationmake :wave:

That's a terrific idea. Can you please provide some example `$GPGGA` NMEA messages?

**Comment by generationmake** [comment]
Hi @aentinger 

sample data from ublox NEO-6M
`$GPGGA,114102.00,4838.01728,N,01301.60593,E,1,08,1.25,434.8,M,45.1,M,,*5F`
sample data from RoyalTek RGM-2000
`$GPGGA,111908.952,4838.0060,N,01301.5895,E,1,05,2.4,454.7,M,46.6,M,0.0,0000*7A`

we will have to discuss what to do with the time and location data in the messages.

**Comment by aentinger** [comment]
Good morning @generationmake :wave: ☕ 

Thank you for the sample data. I'd make the `GGA` data available in the same way the `RMC` data is already made available (see [here](https://github.com/107-systems/107-Arduino-NMEA-Parser/blob/mark-gprmc-data-valid/src/ArduinoNmeaParser.h#L45)) - that is in full. The user of the library shall decide wether they want the time and location from the `RMC` or `GPA` message.

**Comment by aentinger** [comment]
Meanwhile, can you please test https://github.com/107-systems/107-Arduino-NMEA-Parser/pull/18 and merge, if it fulfils all your requirements? Otherwise please put your suggestions into that PR 😉
