### ISSUE TITLE
Add support for GLONASS and concurrent receivers

### ISSUE THREAD

**Issue by generationmake** [107-systems/107-Arduino-NMEA-Parser#19]
At the moment only GPS receivers and their output is supported. GLONASS and concurrent receiver produce a different dataset. The messages start with $GNxxx or $GLxxx instead of $GPxxx.

for example the output of a u-blox NEO-M8N:
`$GNRMC,090348.80,A,4838.00682,N,01301.61381,E,1.533,,301020,,,A*61`

please add the support for these receivers.

**Comment by aentinger** [comment]
Hi @generationmake 👋 I'll put in onto the feature list. Do you have such a receiver for testing?

**Comment by generationmake** [comment]
Hi @aentinger 
I have an u-blox NEO-7M which can be switched from GPS to GLONASS and an u-blox NEO-M8N which supports concurrent systems. So yes, I have devices available for testing.
Maybe we could add a list with tested devices.

**Comment by aentinger** [comment]
We definitely should add a list of tested devices within the README 👍
