### ISSUE TITLE
Provide conversion function from RMC Date/Time struct to POSIX timestamp

### ISSUE THREAD

**Issue by generationmake** [107-systems/107-Arduino-NMEA-Parser#20]
The $GPRMC dataset also contains the date. Until now this is not yet decoded. So please add this feature.

At the moment time information is returned in 3 variables containing hours, minutes and seconds. Including the date this will be 6 variables. This is not very comfortable if you want to pass the time information on to other functions. Maybe you could combine these functions all in one variable or structure. Maybe as integer like in the unix timestamp.

**Comment by aentinger** [comment]
Hi @generationmake :wave:

This is not correct. The date is already decoded and stored in a [structure](https://github.com/107-systems/107-Arduino-NMEA-Parser/blob/master/src/nmea/Types.h#L30:L35). A function converting this to a POSIX timestamp would make sense though.

**Comment by generationmake** [comment]
Hi @aentinger 
sorry, i somehow missed that date is already decoded. But I found an issue with it:
When there is only a time fix after startup date values are all -1 although the could be decoded correctly. 
At least the u-blox NEO-7M sends a date when it has a time.
Do you need sample data?

**Comment by aentinger** [comment]
No worries. I think I know the source of the issue you've observed. Would you mind to open a new issue (Containing "Bug" in the title) including GPRMC sample data and expected parser output?

@per1234 can you replace the default GitHub labels with others which are a bit more useful? I'd need at least a "Bug Report" and a "Feature Request" label, if you know other labels that make sense then please add them too.
