### ISSUE TITLE
Bug: date not decoded when no gps fix

### ISSUE THREAD

**Issue by generationmake** [107-systems/107-Arduino-NMEA-Parser#21]
When there is only a time fix, the date is not decoded. All date values (day, month, year) return -1 until there is a GPS fix. Then the correct values are reported. But the data was also there when there was only a time fix and they could have been decoded.

sample string of u-blox NEO-7M:
`$GPRMC,144602.00,V,,,,,,,011120,,,N*7B`

**Comment by aentinger** [comment]
Thank you very much for documenting this issue. I'll be looking into it :wave:
