### ISSUE TITLE
Incompatible library (UNO R3)

### ISSUE THREAD

**Issue by victorlysak** [107-systems/107-Arduino-NMEA-Parser#69]
Arduino ide desigtates this library as incompatibe with UNO and when compiling gives the foll. erors:
In file included from /home/vic/Arduino/libraries/107-Arduino-NMEA-Parser/examples/NMEA-Basic/NMEA-Basic.ino:21:0:
/home/.../Arduino/libraries/107-Arduino-NMEA-Parser/src/ArduinoNmeaParser.h:20:10: fatal error: functional: No such file or directory
 #include <functional>
          ^~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Uno.

What can I do to make it work with UNO, I need some library that uses Galileo and GPS.

thank you

**Comment by aentinger** [comment]
This library is incompatible with Arduino Uno and is correctly declared so. Why are you surprised?
